name: Flutter Tests

on:
  push:
    branches: [ main, 7-add-ci-integration-for-unit-tests]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.2'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Format code
      run: dart format .
    
    - name: Analyze project source
      run: flutter analyze --no-fatal-infos
    
    - name: Run tests
      run: flutter test --reporter=expanded
